import GridLossEnum from './GridLossEnum';

const Regions = {
  CALIFORNIA: {
    id: 1,
    slug: 'CA',
    label: 'California',
    defaults: 'eere-defaults-california',
    rdf: 'rdf_california_2015',
    original_slug: 'CA',
    grid_loss: GridLossEnum.Western,
  },
  GREAT_LAKES_MID_ATLANTIC: {
    id: 2,
    slug: 'EMW',
    label: 'Great Lakes / Mid-Atlantic',
    defaults: 'eere-defaults-great-lakes-mid-atlantic',
    rdf: 'rdf_great-lakes-mid-atlantic_2015',
    original_slug: 'EMW',
    grid_loss: GridLossEnum.Eastern,
  },
  NORTHEAST: {
    id: 3,
    slug: 'NE',
    label: 'Northeast',
    defaults: 'eere-defaults-northeast',
    rdf: 'rdf_northeast_2015',
    original_slug: 'NE',
    grid_loss: GridLossEnum.Eastern,
  },
  NORTHWEST: {
    id: 4,
    slug: 'NW',
    label: 'Northwest',
    defaults: 'eere-defaults-northwest',
    rdf: 'rdf_northwest_2015',
    original_slug: 'NW',
    grid_loss: GridLossEnum.Western,
  },
  ROCKY_MOUNTAINS: {
    id: 5,
    slug: 'RM',
    label: 'Rocky Mountains',
    defaults: 'eere-defaults-rocky-mountains',
    rdf: 'rdf_rocky-mountains_2015',
    original_slug: 'RM',
    grid_loss: GridLossEnum.Western,
  },
  LOWER_MIDWEST: {
    id: 6,
    slug: 'SC',
    label: 'Lower Midwest',
    defaults: 'eere-defaults-lower-midwest',
    rdf: 'rdf_lower-midwest_2015',
    original_slug: 'SC',
    grid_loss: GridLossEnum.Eastern,
  },
  SOUTHEAST: {
    id: 7,
    slug: 'SE',
    label: 'Southeast',
    defaults: 'eere-defaults-southeast',
    rdf: 'rdF_southeast_2015',
    original_slug: 'SE',
    grid_loss: GridLossEnum.Eastern,
  },
  SOUTHWEST: {
    id: 8,
    slug: 'SW',
    label: 'Southwest',
    defaults: 'eere-defaults-southwest',
    rdf: 'rdf_southwest_2015',
    original_slug: 'AZNM',
    grid_loss: GridLossEnum.Western,
  },
  TEXAS: {
    id: 9,
    slug: 'TX',
    label: 'Texas',
    defaults: 'eere-defaults-texas',
    rdf: 'rdf_texas_2015',
    original_slug: 'TX',
    grid_loss: GridLossEnum.Texas_ERCOT,
  },
  UPPER_MIDWEST: {
    id: 10,
    slug: 'WMW',
    label: 'Upper Midwest',
    defaults: 'eere-defaults-upper-midwest',
    rdf: 'rdf_upper-midwest_2015',
    original_slug: 'WMW',
    grid_loss: GridLossEnum.Eastern,
  },
}

export default Regions;